In [1]:
round(678.89, ndigits=None)

679

In [2]:
round(34567.2345678, ndigits=2)

34567.23

In [3]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [4]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [5]:
print("apple", "banana", "cherry")


apple banana cherry


In [6]:
print("apple", "banana", "cherry", sep=", ")


apple, banana, cherry


In [10]:
print("Hello, world!", flush=True)


Hello, world!


In [3]:
def least_difference(a, b, c):
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

In [6]:
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7), # Python allows trailing commas in argument lists. How nice is that?
)

9 0 1


In [7]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)



In [14]:
def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5


In [20]:
print(
    max(100, 51, 14),
    max(100, 51, 14,key=mod_5),
    sep='\n',
)


100
14


In [22]:
def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1), 
    sep='\n', # '\n' is the newline character - it starts a new line
)

5
25


In [23]:
round(343456.445678,-1)

343460.0

In [24]:
'''ndigits=-1 rounds to the nearest 10, ndigits=-2 rounds to the nearest 100 and so on.''' 

'ndigits=-1 rounds to the nearest 10, ndigits=-2 rounds to the nearest 100 and so on.'

In [1]:

hands = [
    ['J', 'Q', 'K'],
    ['2', '2', '2'],
    ['6', 'A', 'K'], # (Comma after the last element is optional)
]

In [2]:
hands

[['J', 'Q', 'K'], ['2', '2', '2'], ['6', 'A', 'K']]

In [4]:
my_favourite_things = [32, 'raindrops on roses', help]
my_favourite_things


[32,
 'raindrops on roses',
 Type help() for interactive help, or help(object) for help about object.]

In [5]:
x = 12
# x is a real number, so its imaginary part is 0.
print(x.imag)

0


In [9]:
c = 12 + 3j
print(c.imag)
print(c.real)
print(c)

3.0
12.0
(12+3j)


###  A function attached to an object is called a method. (Non-function things attached to an object, such as imag, are called attributes).

In [10]:
x=12
x.bit_length()

4

In [17]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [15]:
planets.append('Pluto')

In [14]:

help(planets.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [16]:
planets

['Mercury',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Pluto']

In [18]:
num=[1,2,3,45,6,8,90,678]

In [19]:
num

[1, 2, 3, 45, 6, 8, 90, 678]

In [20]:
planets.index('Earth')

2

In [21]:
"Calbefraques" in planets

False

In [22]:
help(planets)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [23]:
t=1,2,3
t

(1, 2, 3)

Tuples are often used for functions that have multiple return values.

For example, the as_integer_ratio() method of float objects returns a numerator and a denominator in the form of a tuple:

In [31]:
x = 0.125
x.as_integer_ratio()

(1, 8)

In [32]:
numerator, denominator = x.as_integer_ratio()
print(numerator / denominator)

0.125


###  classic Stupid Python Trick™ for swapping two variables!

In [33]:
a = 1
b = 0
a, b = b, a
print(a, b)

0 1


In [34]:
a = [1, 2, 3]
b = [1, [2, 3]]
c = []
d = [1, 2, 3][1:]

In [35]:
lengths = [len(a),len(b),len(c),len(d)]

In [36]:
lengths

[3, 2, 0, 2]

In [3]:
hello="""hello
world"""
print(hello)

hello
world


In [4]:
triplequoted_hello = """hello
world"""
print(triplequoted_hello)


triplequoted_hello == hello

hello
world


True

In [6]:
print("hello")
print("world")
print("hello", end='   ')
print("pluto", end='')

hello
world
hello   pluto

In [11]:
import random

print(random.randint(1, 10, 5))  # Gives a random number between 1 and 10, including both


TypeError: Random.randint() takes 3 positional arguments but 4 were given

In [14]:
import numpy as np

print(np.random.randint(1, 10,5))  # Gives a random number from 1 to 9 (10 is excluded)


[8 8 1 8 5]


In [15]:
np.random.randint(1, 10,5)

array([4, 5, 8, 4, 6], dtype=int32)

In [22]:
claim = "Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [20]:
claim.index('p')

11

In [27]:
claim.startswith("P")

False

In [30]:
claim.endswith("planet!")

True

In [37]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')
year, month , day

('1956', '01', '31')

In [38]:
'/'.join([month, day, year])

'01/31/1956'

In [39]:
datestr

'1956-01-31'

In [49]:


planet="pluto"
pluto_mass = 1.323 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
#         2 decimal points   3 decimal points, format as percent     separate with commas
"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)

"pluto weighs about 1.3e+22 kilograms (0.222% of Earth's mass). It is home to 52,910,390 Plutonians."

In [50]:
e = '\n'
length = len(e)
length

1

In [51]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [53]:

import numpy

xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]
